### ISSUE TITLE
Error encountered when running "make" to compile

### ISSUE THREAD

**Issue by DarrenZhang01** [neubig/pialign#12]
Hi, I tried to compile the program using "make" as described on [http://www.phontron.com/pialign/#download](http://www.phontron.com/pialign/#download), but I came across  the following error. Could you help look it up? Thanks.
<img width="804" alt="error" src="https://user-images.githubusercontent.com/29133834/54079042-3dc58200-42a2-11e9-8b2a-b30d3dadf2b9.png">

**Comment by loretoparisi** [comment]
Got the same error on Ubuntu Docker 18.04:

```sh
/bin/bash ../../libtool --tag=CXX   --mode=compile g++ -DHAVE_CONFIG_H -I. -I../../src/include/pialign  -I./../include   -g -O2 -MT pialign.lo -MD -MP -MF .deps/pialign.Tpo -c -o pialign.lo pialign.cc
libtool: compile:  g++ -DHAVE_CONFIG_H -I. -I../../src/include/pialign -I./../include -g -O2 -MT pialign.lo -MD -MP -MF .deps/pialign.Tpo -c pialign.cc  -fPIC -DPIC -o .libs/pialign.o
In file included from ./../include/pialign/pialign.h:5:0,
                 from pialign.cc:8:
./../include/pialign/dirichletdist.h: In member function 'std::vector<double> pialign::DirichletDist<T>::getAllProbs() const':
./../include/pialign/dirichletdist.h:43:30: error: request for member 'size' in 'pialign::ret', which is of non-class type 'std::vector<double>()'
         for(T i = 0; i < ret.size(); i++)
                              ^~~~
Makefile:320: recipe for target 'pialign.lo' failed
make[2]: *** [pialign.lo] Error 1
make[2]: Leaving directory '/root/src/lib'
Makefile:255: recipe for target 'all-recursive' failed
make[1]: *** [all-recursive] Error 1
make[1]: Leaving directory '/root/src'
Makefile:372: recipe for target 'all-recursive' failed
make: *** [all-recursive] Error 1
```

**Comment by neubig** [comment]
I've created a new release 0.2.5 and updated the code on github and things seem to work for me. If they work for you, please confirm and close the issue. If they don't work, could you please give the full steps needed to reproduce?

**Comment by DarrenZhang01** [comment]
> I've created a new release 0.2.5 and updated the code on github and things seem to work for me. If they work for you, please confirm and close the issue. If they don't work, could you please give the full steps needed to reproduce?

Thanks a lot for the reply! I switched to directly execute the binary file "pialign" under "bin", and it works very well now!
