### ISSUE TITLE
autoconf on macOS

### ISSUE THREAD

**Issue by loretoparisi** [neubig/pialign#13]
when running `autoconf` on macOS

```sh
configure.ac:17: error: possibly undefined macro: AM_INIT_AUTOMAKE
      If this token and others are legitimate, please use m4_pattern_allow.
      See the Autoconf documentation.
configure.ac:23: error: possibly undefined macro: AC_PROG_LIBTOOL

```

**Comment by neubig** [comment]
I ran on MacOS Mojave and didn't get this error. Could you please elaborate about your environment and the steps I could take to reproduce?

**Comment by loretoparisi** [comment]
@neubig hello, so this was before the last updated. At the end I was able to correctly make doing

```sh
cd pialign/
autoreconf -i
./configure
make
make install
```

so I think we can close this! thank you.
